export const newsData = [
  {
    type: 'interview',
    src: 'img/news/news-interview.jpg',
    srcset: 'img/news/news-interview@2x.jpg 2x',
    date: '23/03/2023',
    title: 'Интервью с участницей программы стажировки',
    webp: 'img/news/news-interview.webp 1x, img/news/news-interview@2x.webp 2x',
    text: 'Саша рассказывает, как попала в\u00A0программу и\u00A0как прошла 6-месячная стажировка в\u00A0ISOFound',
  },
  {
    type: 'trips',
    src: 'img/news/news-trips.jpg',
    srcset: 'img/news/news-trips@2x.jpg 2x',
    date: '20/03/2023',
    title: 'Путешествуем по\u00A0Израилю',
    webp: 'img/news/news-trips.webp 1x, img/news/news-trips@2x.webp 2x',
    text: 'Какие места посещают наши студенты весной',
  },
  {
    type: 'voluntering',
    src: 'img/news/news-voluntering.jpg',
    srcset: 'img/news/news-voluntering@2x.jpg 2x',
    date: '17/03/2023',
    title: 'Новая программа волонтёрства',
    webp: 'img/news/news-voluntering.webp 1x, img/news/news-voluntering@2x.webp 2x',
    text: 'Программа помощи детям длительностью 4\u00A0месяца',
  },
  {
    type: 'career',
    src: 'img/news/news-career.jpg',
    srcset: 'img/news/news-career@2x.jpg 2x',
    date: '10/03/2023',
    title: 'Построй свою карьеру',
    webp: 'img/news/news-career.webp 1x, img/news/news-career@2x.webp 2x',
    text: 'Ведущие компании готовы трудоустроить выпускников стажировки',
  },
  {
    type: 'trips',
    src: 'img/news/news-trips.jpg',
    srcset: 'img/news/news-trips@2x.jpg 2x',
    date: '20/03/2023',
    title: 'Путешествуем по\u00A0Израилю',
    webp: 'img/news/news-trips.webp 1x, img/news/news-trips@2x.webp 2x',
    text: 'Какие места посещают наши студенты весной',
  },
  {
    type: 'trips',
    src: 'img/news/news-trips.jpg',
    srcset: 'img/news/news-trips@2x.jpg 2x',
    date: '20/03/2023',
    title: 'Путешествуем по\u00A0Израилю',
    webp: 'img/news/news-trips.webp 1x, img/news/news-trips@2x.webp 2x',
    text: 'Какие места посещают наши студенты весной',
  },
  {
    type: 'interview',
    src: 'img/news/news-interview.jpg',
    srcset: 'img/news/news-interview@2x.jpg 2x',
    date: '23/03/2023',
    title: 'Интервью с участницей программы стажировки',
    webp: 'img/news/news-interview.webp 1x, img/news/news-interview@2x.webp 2x',
    text: 'Саша рассказывает, как попала в\u00A0программу и как прошла 6-месячная стажировка в ISOFound',
  },
  {
    type: 'interview',
    src: 'img/news/news-interview.jpg',
    srcset: 'img/news/news-interview@2x.jpg 2x',
    date: '23/03/2023',
    title: 'Интервью с участницей программы стажировки',
    webp: 'img/news/news-interview.webp 1x, img/news/news-interview@2x.webp 2x',
    text: 'Саша рассказывает, как попала в\u00A0программу и как прошла 6-месячная стажировка в ISOFound',
  },
  {
    type: 'interview',
    src: 'img/news/news-interview.jpg',
    srcset: 'img/news/news-interview@2x.jpg 2x',
    date: '23/03/2023',
    title: 'Интервью с участницей программы стажировки',
    webp: 'img/news/news-interview.webp 1x, img/news/news-interview@2x.webp 2x',
    text: 'Саша рассказывает, как попала в\u00A0программу и как прошла 6-месячная стажировка в ISOFound',
  },
  {
    type: 'voluntering',
    src: 'img/news/news-voluntering.jpg',
    srcset: 'img/news/news-voluntering@2x.jpg 2x',
    date: '17/03/2023',
    title: 'Новая программа волонтёрства',
    webp: 'img/news/news-voluntering.webp 1x, img/news/news-voluntering@2x.webp 2x',
    text: 'Программа помощи детям длительностью 4\u00A0месяца',
  },
  {
    type: 'career',
    src: 'img/news/news-career.jpg',
    srcset: 'img/news/news-career@2x.jpg 2x',
    date: '10/03/2023',
    title: 'Построй свою карьеру',
    webp: 'img/news/news-career.webp 1x, img/news/news-career@2x.webp 2x',
    text: 'Ведущие компании готовы трудоустроить выпускников стажировки',
  },
  {
    type: 'career',
    src: 'img/news/news-career.jpg',
    srcset: 'img/news/news-career@2x.jpg 2x',
    date: '10/03/2023',
    title: 'Построй свою карьеру',
    webp: 'img/news/news-career.webp 1x, img/news/news-career@2x.webp 2x',
    text: 'Ведущие компании готовы трудоустроить выпускников стажировки',
  }
];
